### PR TITLE
Refactor user facing api, so users can use local models by passing a …

### PR DESCRIPTION
**Pull request by fedossa**
…config to model parameter. Also changed the default option to start llama server to false. BotEx now expects that a local model user will have started the llama.cpp server by default..

### CODE REVIEW

**Comment by joachim-gassen** [comment]
Hi there. Looking great. Some issues that I would like to discuss before we take this to main and start with documentation.

1. How can the user provide a local model in the CLI? I thought that we implement the option to provide a string containing the LocalLLM object as JSON. The PR should contain a feasible way to use a 'local' model from the command line.
2. We should try to make the API as close to litellm as possible. litellm offers `api_base` parameter for its completion() call that contains the API URL of the LLM. We could use the same parameter for local models.
3. We should get rid of the terms local and openai. As I see it we currently offer two ways to reference LLMs: litellm or llama.cpp. 
4. If I were to design the API for the llama.cpp part, I would use the `model` and `api_base` parameters for the bot calling functions, assuming that the LLM is already reachable under the URL provided by by the `api_base` parameter. For users that want us to start llama.cpp for them I would most likely implement a separate function that does this. That way, you could  keep the clutter of the local llama.cpp config out of the model string that is required to reach a llama.cpp driven model. 


What do you think?

**Comment by fedossa** [comment]
Hi Joachim, thank you for the feedback! Here are my thoughts on the points that you have raised: 

1. I agree that we should support local models via the CLI. This is on my to-do list. 

2. I can use api_base as the parameter to specify the endpoint for llama.cpp. However, at the moment api_base is not even a parameter that is expected in our api. I would have to get it from "kwargs (dict): Additional keyword arguments to pass on to litellm.completion()." - which could be confusing for users. Does this mean we bring it to the top level?

3. I see the value in moving away from the term openai to remote. However, moving from local to implementation-specific terms like litellm or llama.cpp could shift the user's focus to technical details rather than the practical distinction between local and remote models. llama.cpp only offers a local solution and at the moment, it is the best way to use local models for botex.

4. I’ll move the logic for starting and managing llama.cpp servers into a dedicated manager function. The LocalLLM class will then focus solely on interacting with a running server, simplifying its role and aligning it with the api_base approach.

**Comment by joachim-gassen** [comment]
Ah add about #2. Yes we could bring it to the top level.

**Comment by fedossa** [comment]
Hi Joachim,

I have implemented the changes that we have discussed. I think this PR is ready for a second review. Let me know what you think

**Comment by joachim-gassen** [comment]
Hi there. Thanks. I ended up making more changes then initially intended. You did not implement the separation from llama-server startup and run_bot code. Also, the llama-sever startup code did not parse the environment variables for starting the sever. I also had to do quite some refactoring so that all fits together (sort off). Anyway: pytest passes ;-) S, all is good, right?

**Comment by fedossa** [comment]
Yes great to hear pytest passes :) But I am trying to understand this and maybe I had a different understanding of what separating the llama-server startup and run_bot code means. So in my PR, I had put all things related to managing the llama-server to the LlamaCppServerManager class and defined the two utility functions start and stop llama cpp server. But this does not even get imported in the bot.py.

**Pull request merged**
